name: Sanity Studio Deploy
on:
  push:
    branches:
      - main
    paths:
      - apps/cms/**
      - packages/sanity/**
defaults:
  run:
    working-directory: sanity-studio
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          yarn
      - name: Deploy Sanity
        run: |
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" yarn workspace @fusion/cms deploy
